"""
minijx runtime: what the Python code generated by the `minijx` compiler imports.
"""

# First: the catalog imports it. The only place the version is written:
# the Makefile and the wheel build pass it to the compiler binary.
__version__ = "0.1.0"

from .attrs import Attrs  # noqa: E402
from .catalog import (  # noqa: E402
    Catalog,
    CompileError,
    Component,
    ComponentNotCompiledError,
    ComponentNotFoundError,
)
from .loop import Loop  # noqa: E402
from .runtime import concat, escape, getattr_, getitem, has_attr  # noqa: E402


__all__ = [
    "Catalog", "Component", "ComponentNotCompiledError", "ComponentNotFoundError", "CompileError",
    "Attrs", "Loop", "concat", "escape", "getattr_", "getitem", "has_attr"]
