"""
minijx runtime: what the Python code generated by the `minijx` compiler imports.
"""

# First: the catalog imports it. Keep in sync with MinijxVersion in
# compiler/mjcodegen.pas (the wheel build checks it).
__version__ = "0.1.0"

from .attrs import Attrs  # noqa: E402
from .catalog import (  # noqa: E402
    Catalog,
    CompileError,
    Component,
    ComponentNotCompiledError,
    ComponentNotFoundError,
)
from .loop import Loop  # noqa: E402
from .runtime import concat, escape, getattr_, getitem, has_attr, to_str  # noqa: E402


__all__ = [
    "Catalog", "Component", "ComponentNotCompiledError", "ComponentNotFoundError", "CompileError",
    "Attrs", "Loop", "concat", "escape", "getattr_", "getitem", "has_attr", "to_str"]
