"""
minijx runtime: what the Python code generated by the `minijx` compiler imports.
"""

from pathlib import Path


def _version() -> str:
    """
    The version, which is only written in pyproject.toml.

    From a source checkout (how the tests run, with PYTHONPATH=src, and in
    an editable install) it is read from that file: an installed minijx of
    another version could be in the same environment. Installed from a
    wheel, it comes from the package metadata.
    """
    pyproject = Path(__file__).resolve().parents[2] / "pyproject.toml"
    if pyproject.is_file():
        import tomllib

        project = tomllib.loads(pyproject.read_text(encoding="utf-8")).get("project", {})
        if project.get("name") == "minijx":
            return project["version"]
    from importlib.metadata import PackageNotFoundError, version

    try:
        return version("minijx")
    except PackageNotFoundError:
        return "unknown"


# First: the catalog imports it.
__version__ = _version()

from .attrs import Attrs  # noqa: E402
from .catalog import (  # noqa: E402
    Catalog,
    CompileError,
    Component,
    ComponentNotCompiledError,
    ComponentNotFoundError,
)
from .loop import Loop  # noqa: E402
from .runtime import concat, escape, getattr_, getitem, has_attr  # noqa: E402


__all__ = [
    "Catalog", "Component", "ComponentNotCompiledError", "ComponentNotFoundError", "CompileError",
    "Attrs", "Loop", "concat", "escape", "getattr_", "getitem", "has_attr"]
