"""
minijx runtime: a catalog of compiled components, with the same API shape as
`jx.Catalog`.

    catalog = Catalog("components/", compiler="minijx", site_name="Demo")
    catalog.compile()
    html = catalog.render("pages/home.jx", globals={"user": user}, title="Hi")

A component is named by its path relative to one of the folders, as in Jx:
`"pages/home.jx"`. The catalog finds the Python module minijx generated for
it (`pages/home.py`; `sitemap.xml.jx` -> `sitemap_xml.py`), loads it once,
and calls its `render`.

With `auto_reload=True` (the default) every render checks the modification
times of the module and of every `.jx` copied into it (the module's
`SOURCES`). A changed module is reloaded. A module older than its sources is
recompiled when `compiler` is given, and is an error otherwise.
"""

import os
import re
import shutil
import subprocess
import threading
import types
import typing as t
import uuid
from pathlib import Path

from . import __version__, environment


__all__ = [
    "Catalog",
    "Component",
    "ComponentNotFoundError",
    "ComponentNotCompiledError",
    "CompileError",
    "get_random_id",
]

# Layout of the generated modules; must match `ModuleFormat` in
# src/mjcodegen.pas. A module with another value was generated by a
# different minijx and is treated as stale.
MODULE_FORMAT = 5


class ComponentNotFoundError(LookupError):
    """No folder of the catalog has a `.jx` or compiled module with that name."""


class ComponentNotCompiledError(LookupError):
    """The `.jx` exists, but its module is missing or older than its sources."""


class CompileError(RuntimeError):
    """The minijx binary reported errors; the message lists them."""


def bundled_compiler() -> Path | None:
    """
    The compiler binary shipped inside the wheel (`minijx/bin/minijx`), or,
    in a source checkout, the copy `make build` puts there.
    """
    binary = Path(__file__).parent / "bin" / "minijx"
    if binary.is_file() and os.access(binary, os.X_OK):
        return binary
    return None


def find_compiler() -> str | None:
    """The bundled binary, else a `minijx` in the PATH, else `None`."""
    binary = bundled_compiler()
    if binary is not None:
        return str(binary)
    return shutil.which("minijx")


_checked_compilers: dict[str, None] = {}


def check_compiler(compiler: str) -> None:
    """
    Refuse a binary that generates modules this runtime cannot load, e.g. a
    `minijx` in the PATH from another version. Checked once per path.
    """
    if compiler in _checked_compilers:
        return
    try:
        out = subprocess.run([compiler, "--version"], capture_output=True, text=True).stdout
    except OSError as err:
        raise CompileError(f"Cannot run the minijx compiler at {compiler}: {err}") from err
    m = re.match(r"minijx (\S+) \(module format (\d+)\)", out)
    if not m:
        raise CompileError(f"{compiler} does not look like the minijx compiler (--version: {out!r})")
    if int(m.group(2)) != MODULE_FORMAT:
        raise CompileError(
            f"{compiler} is minijx {m.group(1)}, which generates modules of format "
            f"{m.group(2)}; this runtime (minijx {__version__}) needs format {MODULE_FORMAT}"
        )
    _checked_compilers[compiler] = None


def get_random_id(prefix: str = "id") -> str:
    """A unique string for HTML element ids. Same as Jx's `_get_random_id`."""
    return f"{prefix}-{uuid.uuid4().hex}"


def module_path(jx_path: Path) -> Path:
    """
    Where minijx writes the module for a `.jx` file: same folder, the `.jx`
    dropped, other dots in the name turned into `_`.
    Must match `OutputPath` in `src/mjcodegen.pas`.
    """
    name = jx_path.name
    if name.endswith(".jx"):
        name = name[:-3]
    return jx_path.with_name(name.replace(".", "_") + ".py")


class Component:
    """
    A loaded component module.

    `render` is the generated function. The asset helpers mirror the ones Jx
    puts in the `assets` global of every top-level render.
    """

    __slots__ = ("relpath", "path", "module", "mtime_ns", "sources")

    def __init__(self, relpath: str, path: Path, module: types.ModuleType, mtime_ns: int) -> None:
        self.relpath = relpath
        self.path = path
        self.module = module
        self.mtime_ns = mtime_ns
        self.sources = tuple(path.parent / s for s in getattr(module, "SOURCES", ()))

    def render(self, **kwargs: t.Any) -> str:
        return self.module.render(**kwargs)

    def collect_css(self) -> list[str]:
        return list(self.module.CSS)

    def collect_js(self) -> list[str]:
        return list(self.module.JS)

    def render_css(self) -> str:
        return "\n".join(f'<link rel="stylesheet" href="{url}">' for url in self.collect_css())

    def render_js(self, module: bool = True, defer: bool = True) -> str:
        html = []
        for url in self.collect_js():
            if module:
                html.append(f'<script type="module" src="{url}"></script>')
            elif defer:
                html.append(f'<script src="{url}" defer></script>')
            else:
                html.append(f'<script src="{url}"></script>')
        return "\n".join(html)

    def render_assets(self, module: bool = True, defer: bool = True) -> str:
        return "\n".join([self.render_css(), self.render_js(module=module, defer=defer)]).strip()

    def assets(self) -> dict[str, t.Callable]:
        return {
            "collect_css": self.collect_css,
            "collect_js": self.collect_js,
            "render_css": self.render_css,
            "render_js": self.render_js,
            "render": self.render_assets,
        }


class Catalog:
    def __init__(
        self,
        folder: str | Path | None = None,
        *,
        auto_reload: bool = True,
        compiler: str | Path | bool | None = None,
        filters: dict[str, t.Callable] | None = None,
        tests: dict[str, t.Callable] | None = None,
        **template_globals: t.Any,
    ) -> None:
        """
        Arguments:
            folder:
                Optional folder to search for components; a shortcut for
                calling `add_folder` when only one is used.
            auto_reload:
                Check modification times on every render and reload (or
                recompile, see `compiler`) what changed. Turn it off in
                production.
            compiler:
                The minijx binary used by `compile()` and, with `auto_reload`,
                to recompile a missing or stale module on render. By default
                the one shipped with this package (or a `minijx` in the
                PATH). `False` never compiles: modules must be built ahead.
            filters:
                Extra filters, `{"name": function}`, as in Jx. A filter
                receives the filtered value first. It can replace a builtin
                filter of the same name.
            tests:
                Extra tests, `{"name": function}`, for `x is name` and for
                `select`/`reject`. Tests that minijx compiles into plain Python
                (`defined`, `none`, `in`, `eq`, ...) cannot be replaced.
            **template_globals:
                Variables available to every component, through `_globals`.

        """
        self.folders: list[Path] = []
        self.auto_reload = auto_reload
        if compiler is None:
            self.compiler = find_compiler()
        elif compiler is False:
            self.compiler = None
        else:
            self.compiler = str(compiler)
        self.globals: dict[str, t.Any] = {"_get_random_id": get_random_id, **template_globals}
        if filters or tests:
            all_filters, all_tests = environment.build(filters, tests)
            self.globals[environment.FILTERS_KEY] = all_filters
            self.globals[environment.TESTS_KEY] = all_tests
        self._cache: dict[str, Component] = {}
        self._lock = threading.RLock()
        if folder:
            self.add_folder(folder)

    # Registration

    def add_folder(self, path: str | Path) -> None:
        """
        Add a folder of components to compile and render. Its components are
        imported and rendered by their path relative to it: `"sub/card.jx"`.
        Folders are searched in the order they were added; the first that
        has the component wins.
        """
        folder = Path(path).resolve()
        if not folder.is_dir():
            raise NotADirectoryError(str(folder))
        with self._lock:
            if folder not in self.folders:
                self.folders.append(folder)
                self._cache.clear()

    add_path = add_folder  # alias, as in Jx

    # Compiling

    def compile(self) -> None:
        """
        Compile every folder of the catalog. Raises `CompileError` listing
        every error, after compiling everything that could be compiled.
        """
        if not self.compiler:
            raise FileNotFoundError(
                "No minijx compiler: this installation has no bundled binary and there "
                "is no `minijx` in the PATH, or the Catalog was created with `compiler=False`"
            )
        result = self._run_compiler(self.compiler)
        if result.returncode != 0:
            raise CompileError(self._errors(result))

    def compiler_args(self) -> list[str]:
        """The command line arguments `compile()` passes to the binary."""
        return [str(f) for f in self.folders]

    def _run_compiler(self, compiler: str) -> subprocess.CompletedProcess:
        check_compiler(compiler)
        return subprocess.run(
            [compiler, *self.compiler_args()],
            capture_output=True,
            text=True,
        )

    @staticmethod
    def _errors(result: subprocess.CompletedProcess) -> str:
        errors = [line for line in result.stderr.splitlines() if not line.startswith("minijx: ")]
        return "\n".join(errors) or result.stderr

    # Rendering

    def render(self, relpath: str, globals: dict[str, t.Any] | None = None, **kwargs: t.Any) -> str:
        """
        Render a component by its path relative to its folder, e.g.
        `"sub/component.jx"`. The `.jx` may be left out.

        Arguments:
            relpath:
                The component's path, with `/` as separator.
            globals:
                Extra globals for this render, on top of the catalog's.
            **kwargs:
                The component's arguments. Anything it does not declare in
                its `{# def #}` ends up in its `attrs`.

        """
        co = self.get_component(relpath)
        _globals = {**self.globals, **(globals or {}), "assets": co.assets()}
        return co.render(_globals=_globals, **kwargs)

    def has_component(self, relpath: str) -> bool:
        return self._find(self._normalize(relpath)) is not None

    def get_component(self, relpath: str) -> Component:
        relpath = self._normalize(relpath)
        co = self._cache.get(relpath)
        if co is not None and (not self.auto_reload or self._is_fresh(co)):
            return co

        with self._lock:
            co = self._cache.get(relpath)
            if co is not None and (not self.auto_reload or self._is_fresh(co)):
                return co
            co = self._load(relpath)
            self._cache[relpath] = co
            return co

    # Private

    @staticmethod
    def _normalize(relpath: str) -> str:
        relpath = relpath.replace("\\", "/").strip("/")
        if not relpath.endswith(".jx"):
            relpath += ".jx"
        return relpath

    def _find(self, relpath: str) -> tuple[Path, Path] | None:
        """(jx path, module path) in the first folder that has either file."""
        for folder in self.folders:
            jx = (folder / relpath).resolve()
            if not jx.is_relative_to(folder):
                continue
            py = module_path(jx)
            if jx.is_file() or py.is_file():
                return jx, py
        return None

    def _is_fresh(self, co: Component) -> bool:
        try:
            mtime = co.path.stat().st_mtime_ns
        except FileNotFoundError:
            return False
        if mtime != co.mtime_ns:
            return False
        return not self._sources_newer(co.sources, mtime)

    @staticmethod
    def _sources_newer(sources: t.Iterable[Path], mtime_ns: int) -> bool:
        for src in sources:
            try:
                if src.stat().st_mtime_ns > mtime_ns:
                    return True
            except FileNotFoundError:
                return True
        return False

    def _load(self, relpath: str) -> Component:
        found = self._find(relpath)
        if found is None:
            raise ComponentNotFoundError(relpath)
        jx, py = found

        if self.auto_reload:
            stale = not py.is_file() or (
                jx.is_file() and jx.stat().st_mtime_ns > py.stat().st_mtime_ns
            )
            if not stale:
                module = self._exec(py)
                sources = [py.parent / s for s in getattr(module, "SOURCES", ())]
                stale = (
                    getattr(module, "MINIJX_FORMAT", None) != MODULE_FORMAT
                    or self._sources_newer(sources, py.stat().st_mtime_ns)
                )
            if stale:
                self._compile_for(relpath, py)
        elif not py.is_file():
            raise ComponentNotCompiledError(f"{relpath}: {py.name} is missing; run minijx")

        mtime = py.stat().st_mtime_ns
        module = self._exec(py)
        if getattr(module, "MINIJX_FORMAT", None) != MODULE_FORMAT:
            raise ComponentNotCompiledError(
                f"{relpath}: {py.name} was generated by a different version of minijx; recompile it"
            )
        return Component(relpath, py, module, mtime)

    def _compile_for(self, relpath: str, py: Path) -> None:
        """
        Run the compiler over everything. Only a failure to (re)write this
        component's module is an error here: a broken file elsewhere must not
        take down the components that do not use it.
        """
        if not self.compiler:
            raise ComponentNotCompiledError(
                f"{relpath}: the compiled module is missing or older than its .jx sources; "
                f"run `minijx {' '.join(self.compiler_args())}` or call `catalog.compile()`"
            )
        before = py.stat().st_mtime_ns if py.is_file() else None
        result = self._run_compiler(self.compiler)
        written = py.is_file() and py.stat().st_mtime_ns != before
        if not written:
            raise CompileError(self._errors(result))

    @staticmethod
    def _exec(py: Path) -> types.ModuleType:
        """
        Load a module from its source, bypassing `__pycache__`.

        The import system validates a cached `.pyc` by the source's mtime in
        whole seconds and its size. A module recompiled within the same
        second to the same size (`"old"` -> `"new"`) would silently keep the
        old bytecode.
        """
        name = f"minijx_component_{abs(hash(os.fspath(py)))}"
        module = types.ModuleType(name)
        module.__file__ = os.fspath(py)
        code = compile(py.read_bytes(), os.fspath(py), "exec")
        exec(code, module.__dict__)
        return module
