"""
minijx runtime: a catalog of compiled components, with the same API shape as
`jx.Catalog`.

    catalog = Catalog("components/", compiler="minijx", site_name="Demo")
    catalog.compile()
    html = catalog.render("pages/home.jx", globals={"user": user}, title="Hi")

A component is named by its path relative to one of the folders, as in Jx:
`"pages/home.jx"`. The catalog finds the Python module minijx generated for
it (`pages/home.py`; `sitemap.xml.jx` -> `sitemap_xml.py`), loads it once,
and calls its `render`.

With `auto_reload=True` (the default) every render checks the modification
times of the module and of every `.jx` copied into it (the module's
`SOURCES`). A changed module is reloaded. A module older than its sources is
recompiled when `compiler` is given, and is an error otherwise.

With autoescape (on by default for `.jx`, `.html.jx` and `.xml.jx` files),
`{{ }}` escapes what it renders, as Jx does, and `render` returns `Markup`.
"""

import hashlib
import os
import re
import shutil
import subprocess
import tempfile
import threading
import types
import typing as t
import uuid
import weakref
from pathlib import Path

from markupsafe import Markup

from . import __version__, environment
from .debug import rewrite_traceback
from .runtime import merge_attrs


__all__ = [
    "Catalog",
    "Component",
    "ComponentNotFoundError",
    "ComponentNotCompiledError",
    "CompileError",
    "get_random_id",
]

# Layout of the generated modules; must match `ModuleFormat` in
# compiler/mjcompiler.pas. A module with another value was generated by a
# different minijx and is treated as stale.
MODULE_FORMAT = 9

# The extensions whose components are compiled with autoescape, unless the
# catalog is given others: `card.jx` counts as `jx`, `page.html.jx` as
# `html`, `feed.xml.jx` as `xml`. Must match the default in compiler/minijx.lpr.
AUTOESCAPE = ("html", "jx", "xml")

# Statements a custom tag cannot shadow. Must match `ReservedTags` in
# compiler/mjparser.pas.
RESERVED_TAGS = frozenset((
    "if", "elif", "else", "for", "set", "do", "filter", "call", "slot", "fill", "raw",
    "def", "import", "css", "js", "extends", "include", "macro", "block", "with",
    "autoescape", "from", "trans", "pluralize", "break", "continue", "print", "debug",
    "namespace", "caller", "true", "false",
))
TAGS_KEY = "__minijx_tags__"


def check_tags(tags: "dict[str, t.Callable]") -> tuple[str, ...]:
    """The names of the custom tags, sorted (as the compiler writes them in
    `TAGS`). Raises `ValueError` for a name that cannot be a tag and
    `TypeError` for a function that is not callable."""
    for name, func in tags.items():
        if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", name):
            raise ValueError(f"{name!r} cannot be a tag: not a valid name")
        if name in RESERVED_TAGS:
            raise ValueError(f"{name!r} cannot be a tag: a builtin statement")
        if name.startswith("end"):
            raise ValueError(f"{name!r} cannot be a tag: it starts with `end`, which closes a block")
        if not callable(func):
            raise TypeError(f"The function of the tag {name!r} is not callable")
    return tuple(sorted(tags))


# Filters that the compiler trusts to return safe markup, so it does not
# escape their result again: replacing them would open a hole.
TRUSTED_FILTERS = ("e", "escape", "forceescape", "safe")


def normalize_autoescape(value: "bool | t.Iterable[str] | None") -> tuple[str, ...]:
    """`True` -> the default extensions, `False`/`None` -> none, else the
    extensions given, without dots, lowercase, sorted (as the compiler
    writes them in `AUTOESCAPE`)."""
    if value is True:
        return AUTOESCAPE
    if not value:
        return ()
    if isinstance(value, str):
        value = value.split(",")
    exts = {ext.strip().lstrip(".").lower() for ext in value}
    exts.discard("")
    for ext in exts:
        if not re.fullmatch(r"[a-z0-9_-]+", ext):
            raise ValueError(f"Invalid extension for autoescape: {ext!r}")
    return tuple(sorted(exts))


class ComponentNotFoundError(LookupError):
    """No folder of the catalog has a `.jx` or compiled module with that name."""


class ComponentNotCompiledError(LookupError):
    """The `.jx` exists, but its module is missing or older than its sources."""


class CompileError(RuntimeError):
    """The minijx binary reported errors; the message lists them."""


def bundled_compiler() -> Path | None:
    """
    The compiler binary shipped inside the wheel (`minijx/bin/minijx`), or,
    in a source checkout, the copy `make build` puts there.
    """
    binary = Path(__file__).parent / "bin" / "minijx"
    if binary.is_file() and os.access(binary, os.X_OK):
        return binary
    return None


def find_compiler() -> str | None:
    """The bundled binary, else a `minijx` in the PATH, else `None`."""
    binary = bundled_compiler()
    if binary is not None:
        return str(binary)
    return shutil.which("minijx")


_checked_compilers: dict[str, None] = {}


def check_compiler(compiler: str) -> None:
    """
    Refuse a binary that generates modules this runtime cannot load, e.g. a
    `minijx` in the PATH from another version. Checked once per path.
    """
    if compiler in _checked_compilers:
        return
    try:
        out = subprocess.run([compiler, "--version"], capture_output=True, text=True).stdout
    except OSError as err:
        raise CompileError(f"Cannot run the minijx compiler at {compiler}: {err}") from err
    m = re.match(r"minijx (\S+) \(module format (\d+)\)", out)
    if not m:
        raise CompileError(f"{compiler} does not look like the minijx compiler (--version: {out!r})")
    if int(m.group(2)) != MODULE_FORMAT:
        raise CompileError(
            f"{compiler} is minijx {m.group(1)}, which generates modules of format "
            f"{m.group(2)}; this runtime (minijx {__version__}) needs format {MODULE_FORMAT}"
        )
    _checked_compilers[compiler] = None


def get_random_id(prefix: str = "id") -> str:
    """A unique string for HTML element ids. Same as Jx's `_get_random_id`."""
    return f"{prefix}-{uuid.uuid4().hex}"


def output_names(folders: "t.Sequence[Path]") -> list[str]:
    """
    The subfolder of the output folder for each folder of components: its
    name, with `-2`, `-3`... when an earlier folder has the same one.
    Must match `OutputNames` in `compiler/mjcompiler.pas`.
    """
    names: list[str] = []
    for folder in folders:
        base = folder.name or "root"
        name, n = base, 1
        while name in names:
            n += 1
            name = f"{base}-{n}"
        names.append(name)
    return names


def module_path(jx_path: Path) -> Path:
    """
    Where minijx writes the module for a `.jx` file: same folder, the `.jx`
    dropped, other dots in the name turned into `_`.
    Must match `OutputPath` in `compiler/mjcompiler.pas`.
    """
    name = jx_path.name
    if name.endswith(".jx"):
        name = name[:-3]
    return jx_path.with_name(name.replace(".", "_") + ".py")


class Component:
    """
    A loaded component module.

    `render` is the generated function. The asset helpers mirror the ones Jx
    puts in the `assets` global of every top-level render.
    """

    __slots__ = (
        "relpath", "path", "module", "mtime_ns", "sources", "escaped", "_path_str", "_assets",
    )

    def __init__(self, relpath: str, path: Path, module: types.ModuleType, mtime_ns: int) -> None:
        self.relpath = relpath
        self.path = path
        self.module = module
        self.mtime_ns = mtime_ns
        # Plain strings: with auto_reload these are stat'ed on every render,
        # and os.stat on a str skips the Path machinery.
        self._path_str = os.fspath(path)
        self.sources = tuple(os.path.join(path.parent, s) for s in getattr(module, "SOURCES", ()))
        self._assets: dict[str, t.Callable] | None = None
        # Compiled with autoescape: its output is markup.
        self.escaped: bool = getattr(module, "ESCAPED", False)

    def render(self, **kwargs: t.Any) -> str:
        html = self.module.render(**kwargs)
        return Markup(html) if self.escaped else html

    def collect_css(self) -> list[str]:
        return list(self.module.CSS)

    def collect_js(self) -> list[str]:
        return list(self.module.JS)

    def render_css(self) -> Markup:
        return Markup("\n".join(f'<link rel="stylesheet" href="{url}">' for url in self.collect_css()))

    def render_js(self, module: bool = True, defer: bool = True) -> Markup:
        html = []
        for url in self.collect_js():
            if module:
                html.append(f'<script type="module" src="{url}"></script>')
            elif defer:
                html.append(f'<script src="{url}" defer></script>')
            else:
                html.append(f'<script src="{url}"></script>')
        return Markup("\n".join(html))

    def render_assets(self, module: bool = True, defer: bool = True) -> Markup:
        return Markup(
            "\n".join([self.render_css(), self.render_js(module=module, defer=defer)]).strip()
        )

    def assets(self) -> dict[str, t.Callable]:
        """The `assets` global. Built once: every render of this component shares it."""
        if self._assets is None:
            self._assets = {
                "collect_css": self.collect_css,
                "collect_js": self.collect_js,
                "render_css": self.render_css,
                "render_js": self.render_js,
                "render": self.render_assets,
            }
        return self._assets


class Catalog:
    def __init__(
        self,
        folder: str | Path | None = None,
        *,
        auto_reload: bool = True,
        compiler: str | Path | bool | None = None,
        filters: dict[str, t.Callable] | None = None,
        tests: dict[str, t.Callable] | None = None,
        autoescape: "bool | t.Iterable[str]" = True,
        tags: "dict[str, t.Callable] | None" = None,
        output: "str | Path | None" = None,
        **template_globals: t.Any,
    ) -> None:
        """
        Arguments:
            folder:
                Optional folder to search for components; a shortcut for
                calling `add_folder` when only one is used.
            auto_reload:
                Check modification times on every render and reload (or
                recompile, see `compiler`) what changed. Turn it off in
                production.
            compiler:
                The minijx binary used by `compile()` and, with `auto_reload`,
                to recompile a missing or stale module on render. By default
                the one shipped with this package (or a `minijx` in the
                PATH). `False` never compiles: modules must be built ahead.
            filters:
                Extra filters, `{"name": function}`, as in Jx. A filter
                receives the filtered value first. It can replace a builtin
                filter of the same name.
            tests:
                Extra tests, `{"name": function}`, for `x is name` and for
                `select`/`reject`. Tests that minijx compiles into plain Python
                (`defined`, `none`, `in`, `eq`, ...) cannot be replaced.
            autoescape:
                The extensions of the components whose `{{ }}` escape what
                they render, as Jx's autoescape: the one before `.jx`, or
                `jx` if there is none (`card.jx` is `jx`, `page.html.jx` is
                `html`, `mail.txt.jx` is `txt`). `True`, the default, is
                `("html", "jx", "xml")`; `False` turns it off everywhere.
                With autoescape, the filters `e`, `escape`, `forceescape`
                and `safe` cannot be replaced.
            tags:
                Custom block tags, `{"name": function}`:
                `{% name args %}body{% endname %}` calls
                `function(args, caller=body, template="dir/file.jx")`, where
                `body()` renders the body, only if the function calls it.
                What the function returns is rendered, escaped unless it is
                markup (the body is, with autoescape).
            output:
                Where the compiled modules go. By default, next to each
                `.jx`. With a folder, those of each folder of components go
                to `output/<the folder's name>/` (`-2`, `-3`... when two
                have the same name), in the same layout.
            **template_globals:
                Variables available to every component, through `_globals`.
                `catalog.globals` can be changed later.

        Filters, tests and tags can also be added later, with `add_filters`,
        `add_tests` and `add_tags`.

        """
        self.folders: list[Path] = []
        self._output_names: list[str] = []
        self.output = Path(output).resolve() if output is not None else None
        self.auto_reload = auto_reload
        if compiler is None:
            self.compiler = find_compiler()
        elif compiler is False:
            self.compiler = None
        else:
            self.compiler = str(compiler)
        self.autoescape = normalize_autoescape(autoescape)
        self.globals: dict[str, t.Any] = {"_get_random_id": get_random_id, **template_globals}
        self._filters: dict[str, t.Callable] = {}
        self._tests: dict[str, t.Callable] = {}
        self._tags: dict[str, t.Callable] = {}
        self.tags: tuple[str, ...] = ()
        self._cache: dict[str, Component] = {}
        self._strings: dict[str, Component] = {}
        self._strings_dir: Path | None = None
        self._lock = threading.RLock()
        if filters or tests:
            self._set_env({**(filters or {})}, {**(tests or {})})
        if tags:
            self.add_tags(tags)
        if folder:
            self.add_folder(folder)

    # Registration

    def add_folder(self, path: str | Path) -> None:
        """
        Add a folder of components to compile and render. Its components are
        imported and rendered by their path relative to it: `"sub/card.jx"`.
        Folders are searched in the order they were added; the first that
        has the component wins.
        """
        folder = Path(path).resolve()
        if not folder.is_dir():
            raise NotADirectoryError(str(folder))
        with self._lock:
            if folder not in self.folders:
                self.folders.append(folder)
                self._output_names = output_names(self.folders)
                self._cache.clear()

    add_path = add_folder  # alias, as in Jx

    def add_filters(self, filters: "dict[str, t.Callable]") -> None:
        """
        Add filters, `{"name": function}`, as the `filters` argument does.
        Components already loaded use them from their next render.
        """
        self._set_env({**self._filters, **filters}, self._tests)

    def add_tests(self, tests: "dict[str, t.Callable]") -> None:
        """Add tests, `{"name": function}`, as the `tests` argument does."""
        self._set_env(self._filters, {**self._tests, **tests})

    def add_tags(self, tags: "dict[str, t.Callable]") -> None:
        """
        Add custom tags, `{"name": function}`, as the `tags` argument does.
        A new tag name changes how the components compile: modules compiled
        before it are stale, and are recompiled (or refused) when loaded.
        """
        all_tags = {**self._tags, **tags}
        names = check_tags(all_tags)
        with self._lock:
            self._tags = all_tags
            self.globals[TAGS_KEY] = dict(all_tags)
            if names != self.tags:
                self.tags = names
                self._cache.clear()

    def _set_env(self, filters: "dict[str, t.Callable]", tests: "dict[str, t.Callable]") -> None:
        if self.autoescape:
            trusted = sorted(set(TRUSTED_FILTERS) & filters.keys())
            if trusted:
                raise ValueError(
                    f"Cannot replace the filter(s) {', '.join(map(repr, trusted))} with "
                    "autoescape: the compiled code trusts them to return safe markup"
                )
        all_filters, ae_filters, all_tests = environment.build(filters, tests)
        with self._lock:
            self._filters, self._tests = dict(filters), dict(tests)
            self.globals[environment.FILTERS_KEY] = all_filters
            self.globals[environment.FILTERS_AE_KEY] = ae_filters
            self.globals[environment.TESTS_KEY] = all_tests

    # Compiling

    def compile(self) -> None:
        """
        Compile every folder of the catalog. Raises `CompileError` listing
        every error, after compiling everything that could be compiled.
        """
        if not self.folders:
            return
        if not self.compiler:
            raise FileNotFoundError(
                "No minijx compiler: this installation has no bundled binary and there "
                "is no `minijx` in the PATH, or the Catalog was created with `compiler=False`"
            )
        result = self._run_compiler(self.compiler)
        if result.returncode != 0:
            raise CompileError(self._errors(result))

    def compiler_args(self) -> list[str]:
        """The command line arguments `compile()` passes to the binary."""
        args = [f"--autoescape={','.join(self.autoescape)}", f"--tags={','.join(self.tags)}"]
        if self.output is not None:
            args.append(f"--output={self.output}")
        return [*args, *(str(f) for f in self.folders)]

    def _run_compiler(self, compiler: str) -> subprocess.CompletedProcess:
        check_compiler(compiler)
        return subprocess.run(
            [compiler, *self.compiler_args()],
            capture_output=True,
            text=True,
        )

    @staticmethod
    def _errors(result: subprocess.CompletedProcess) -> str:
        errors = [line for line in result.stderr.splitlines() if not line.startswith("minijx: ")]
        return "\n".join(errors) or result.stderr

    # Rendering

    def render(self, relpath: str, globals: dict[str, t.Any] | None = None, **kwargs: t.Any) -> str:
        """
        Render a component by its path relative to its folder, e.g.
        `"sub/component.jx"`. The `.jx` may be left out.

        Arguments:
            relpath:
                The component's path, with `/` as separator.
            globals:
                Extra globals for this render, on top of the catalog's.
            **kwargs:
                The component's arguments. Anything it does not declare in
                its `{# def #}` ends up in its `attrs`.

        An error while rendering has a traceback that points to the lines
        of the templates, not to the compiled code (see `debug.py`).
        """
        return self._render(self.get_component(relpath), globals, kwargs)

    def render_string(self, source: str, globals: dict[str, t.Any] | None = None, **kwargs: t.Any) -> str:
        """
        Render a component from its source, as `render` renders one from a
        file. Its imports are looked for in the catalog's folders.

        The source is written to a temporary folder and compiled once: later
        renders of the same source reuse it (recompiled, with `auto_reload`,
        when a component it imports changes). Compiling takes a few
        milliseconds, so this is for tests, snippets and sources that
        repeat, not for a different text on every call.
        """
        return self._render(self._string_component(source), globals, kwargs)

    def _render(self, co: "Component", globals: dict[str, t.Any] | None, kwargs: dict[str, t.Any]) -> str:
        if "attrs" in kwargs:
            kwargs = merge_attrs(kwargs.pop("attrs"), kwargs)
        _globals = {**self.globals, **(globals or {}), "assets": co.assets()}
        try:
            return co.render(_globals=_globals, **kwargs)
        except Exception as exc:
            raise rewrite_traceback(exc)  # noqa: B904  the same exception

    def _string_component(self, source: str) -> "Component":
        key = hashlib.sha256(source.encode("utf-8")).hexdigest()[:20]
        co = self._strings.get(key)
        if co is not None and (not self.auto_reload or self._is_fresh(co)):
            return co
        with self._lock:
            if not self.compiler:
                raise ComponentNotCompiledError("render_string needs the minijx compiler")
            if self._strings_dir is None:
                self._strings_dir = Path(tempfile.mkdtemp(prefix="minijx-strings-"))
                weakref.finalize(self, shutil.rmtree, self._strings_dir, ignore_errors=True)
            src = self._strings_dir / "strings"
            out = self._strings_dir / "build"
            src.mkdir(exist_ok=True)
            jx = src / f"s{key}.jx"
            jx.write_text(source, encoding="utf-8")
            check_compiler(self.compiler)
            result = subprocess.run(
                [
                    self.compiler,
                    f"--autoescape={','.join(self.autoescape)}",
                    f"--tags={','.join(self.tags)}",
                    f"--output={out}",
                    f"--only={jx}",
                    str(src),
                    *(str(f) for f in self.folders),
                ],
                capture_output=True,
                text=True,
            )
            if result.returncode != 0:
                raise CompileError(self._errors(result).replace(str(jx), "<string>"))
            py = module_path(out / output_names([src, *self.folders])[0] / jx.name)
            co = Component(f"<string {key}>", py, self._exec(py), py.stat().st_mtime_ns)
            self._strings[key] = co
            return co

    def has_component(self, relpath: str) -> bool:
        return self._find(self._normalize(relpath)) is not None

    def get_component(self, relpath: str) -> Component:
        relpath = self._normalize(relpath)
        co = self._cache.get(relpath)
        if co is not None and (not self.auto_reload or self._is_fresh(co)):
            return co

        with self._lock:
            co = self._cache.get(relpath)
            if co is not None and (not self.auto_reload or self._is_fresh(co)):
                return co
            co = self._load(relpath)
            self._cache[relpath] = co
            return co

    # Private

    @staticmethod
    def _normalize(relpath: str) -> str:
        relpath = relpath.replace("\\", "/").strip("/")
        if not relpath.endswith(".jx"):
            relpath += ".jx"
        return relpath

    def _find(self, relpath: str) -> tuple[Path, Path] | None:
        """(jx path, module path) in the first folder that has either file."""
        for i, folder in enumerate(self.folders):
            jx = (folder / relpath).resolve()
            if not jx.is_relative_to(folder):
                continue
            if self.output is None:
                py = module_path(jx)
            else:
                py = module_path(self.output / self._output_names[i] / jx.relative_to(folder))
            if jx.is_file() or py.is_file():
                return jx, py
        return None

    def _is_fresh(self, co: Component) -> bool:
        try:
            mtime = os.stat(co._path_str).st_mtime_ns
        except FileNotFoundError:
            return False
        if mtime != co.mtime_ns:
            return False
        return not self._sources_newer(co.sources, mtime)

    @staticmethod
    def _sources_newer(sources: t.Iterable[str | Path], mtime_ns: int) -> bool:
        for src in sources:
            try:
                if os.stat(src).st_mtime_ns > mtime_ns:
                    return True
            except FileNotFoundError:
                return True
        return False

    def _load(self, relpath: str) -> Component:
        found = self._find(relpath)
        if found is None:
            raise ComponentNotFoundError(relpath)
        jx, py = found

        # Checked the first time a component is loaded, in any mode, so a
        # module left from another version of the views is never served:
        # it is compiled again, or refused without a compiler. `auto_reload`
        # only decides if this is checked again on every render. A module
        # shipped without its `.jx` is taken as it is.
        if not py.is_file():
            reason = "is missing"
        elif jx.is_file():
            reason = self._stale(jx, py)
        else:
            reason = None
        if reason:
            if not self.compiler:
                raise ComponentNotCompiledError(
                    f"{relpath}: {py.name} {reason}; "
                    f"run `minijx {' '.join(self.compiler_args())}` or call `catalog.compile()`"
                )
            self._compile_for(relpath, py)

        mtime = py.stat().st_mtime_ns
        module = self._exec(py)
        # a module shipped without its `.jx` must still fit this catalog
        reason = self._incompatible(module)
        if reason:
            raise ComponentNotCompiledError(f"{relpath}: {py.name} {reason}; recompile it")
        return Component(relpath, py, module, mtime)

    def _incompatible(self, module: types.ModuleType) -> "str | None":
        if getattr(module, "MINIJX_FORMAT", None) != MODULE_FORMAT:
            return "was generated by a different version of minijx"
        if tuple(sorted(getattr(module, "AUTOESCAPE", ()))) != self.autoescape:
            return (
                f"was compiled with autoescape for {getattr(module, 'AUTOESCAPE', None)!r}, "
                f"this catalog uses {self.autoescape!r}"
            )
        if tuple(sorted(getattr(module, "TAGS", ()))) != self.tags:
            return f"was compiled with the tags {getattr(module, 'TAGS', None)!r}, this catalog has {self.tags!r}"
        return None

    def _stale(self, jx: Path, py: Path) -> "str | None":
        """Why the module of a `.jx` must be compiled again, or `None`."""
        mtime = py.stat().st_mtime_ns
        if jx.stat().st_mtime_ns > mtime:
            return f"is older than {jx.name}"
        module = self._exec(py)
        reason = self._incompatible(module)
        if reason:
            return reason
        if not self._compiled_from(jx, py, module):
            return f"was compiled from another file, {module.SOURCES[-1]!r}"
        if self._sources_newer([py.parent / s for s in getattr(module, "SOURCES", ())], mtime):
            return "is older than a component it imports"
        return None

    @staticmethod
    def _compiled_from(jx: Path, py: Path, module: types.ModuleType) -> bool:
        """
        Whether the module was compiled from this `.jx` (the last of its
        SOURCES), and not from another one with the same name: two folders
        with the same name share an output folder name only when they are
        in different catalogs, e.g. apps in the same project. A module
        shipped without its `.jx` is taken as it is.
        """
        sources = getattr(module, "SOURCES", ())
        if not sources or not jx.is_file():
            return True
        return os.path.realpath(py.parent / sources[-1]) == os.path.realpath(jx)

    def _compile_for(self, relpath: str, py: Path) -> None:
        """
        Run the compiler over everything. Only a failure to (re)write this
        component's module is an error here: a broken file elsewhere must not
        take down the components that do not use it.
        """
        if not self.compiler:
            raise ComponentNotCompiledError(
                f"{relpath}: the compiled module is missing, older than its .jx sources, "
                "or compiled with other autoescape extensions or tags; "
                f"run `minijx {' '.join(self.compiler_args())}` or call `catalog.compile()`"
            )
        before = py.stat().st_mtime_ns if py.is_file() else None
        result = self._run_compiler(self.compiler)
        written = py.is_file() and py.stat().st_mtime_ns != before
        if not written:
            raise CompileError(self._errors(result))

    @staticmethod
    def _exec(py: Path) -> types.ModuleType:
        """
        Load a module from its source, bypassing `__pycache__`.

        The import system validates a cached `.pyc` by the source's mtime in
        whole seconds and its size. A module recompiled within the same
        second to the same size (`"old"` -> `"new"`) would silently keep the
        old bytecode.
        """
        name = f"minijx_component_{abs(hash(os.fspath(py)))}"
        module = types.ModuleType(name)
        module.__file__ = os.fspath(py)
        code = compile(py.read_bytes(), os.fspath(py), "exec")
        exec(code, module.__dict__)
        return module
